name: Build fplll Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Установка зависимостей (без изменений)
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev libmpfr-dev wget

      # Шаг 2: Скачивание и распаковка (без изменений)
      - name: Download and Extract fplll
        run: |
          wget https://github.com/fplll/fplll/releases/download/5.5.0/fplll-5.5.0.tar.gz
          tar -xzvf fplll-5.5.0.tar.gz

      # Шаг 3: Конфигурация, компиляция и УСТАНОВКА в локальную папку
      # ИЗМЕНЕНИЯ ЗДЕСЬ:
      - name: Configure, Build and Install
        run: |
          cd fplll-5.5.0
          # Говорим, что устанавливать нужно в папку 'dist' в корне проекта
          ./configure --prefix=${{ github.workspace }}/dist
          # Собираем проект
          make -j$(nproc)
          # Устанавливаем в указанную папку
          make install

      # Шаг 4: Выгрузка готового бинарного файла
      # ИЗМЕНЕНИЯ ЗДЕСЬ:
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fplll-binary # Имя артефакта остается прежним
          # Путь теперь ведет к исполняемому файлу внутри папки,
          # куда мы все установили.
          path: ${{ github.workspace }}/dist/bin/fplll
